### ISSUE TITLE
打不开爱淘宝的链接

### ISSUE THREAD

**Issue by baoqiaoze** [lbp0200/www.liuboping.com#4]
rt，打不开爱淘宝的链接

**Comment by lbp0200** [comment]
可能确实有问题，不过我可以打开，北京移动。

https://ai.taobao.com/search/index.htm?pid=mm_48510912_36052737_128472059&fcat=3306&key=计算机网络

**Comment by lbp0200** [comment]
也许和地址有关系，我更新地址
https://ai.taobao.com/search/index.htm?key=%E5%9B%BE%E4%B9%A6&pid=mm_48510912_36112080_128622796

**Comment by baoqiaoze** [comment]
额 排查了一下 爱淘宝整个被一个翻墙去广告的host拦截了，关了就好了。
